### ISSUE TITLE
US [QA] Roadmap projet

### ISSUE THREAD

**Issue by MetalBrackets** [BarraDataSquad/bd-documentations#12]
## En tant que PO et dev,

Je veux la vue globale sur la livraison de l'application: DOD de ces livraisons.
Afin de planifier le projet et d'avoir la Roadmap

## 🏁 Definition of Ready (DOR) :

- [ ] Le WBS doit être réalisé
- [ ] J'ai initialisé un atelier

## 💻 Tâches techniques (si nécessaires) :

- [ ] Lire [cet article de roadmap](https://www.productplan.com/learn/example-roadmaps-for-product-managers/) 
- [ ] Créer une documentation et une roadmap

## ✔️ Definition of Done (DOD) :

- [ ] Le code est écrit et documenté.
- [ ] Les tests unitaires sont inclus et réussissent.
- [ ] La fonctionnalité est intégrée dans la branche principale (main).
- [ ] Les tests d'acceptation sont réussis.

## 👍 Critères d'acceptation :

- [ ] J'ai partagé et fait challengé la roadmap à l'ensemble de mon équipe
- [ ] J'ai retravaillé la roadmap avec les retours de mon équipe
